version: '3'
services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: master
    environment:
      - SPARK_MASTER_HOST=master
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/logs
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=/opt/spark/logs
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:4040"   # Spark Master Web UI port
      - "7077:7077"   # Spark Master port
      - "8888:8888"   # Jupyter notebook
    volumes:
      - ./pyspark-jupyter/data:/data
      - spark-logs:/opt/spark/logs
    networks:
      - spark-network
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"   # Jupyter notebook port
    volumes:
      - ./pyspark-jupyter/notebooks:/home/jovyan/work
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  spark-logs:
